local norminette = require("highlight-norminette")
norminette.setup()
vim.api.nvim_create_user_command("NormeEnable", 'require("highlight-norminette").enable', {})
vim.api.nvim_create_user_command("NormeDisable", 'require("highlight-norminette").disable', {})
vim.api.nvim_create_user_command("NormeToggle", 'require("highlight-norminette").toggle', {})
