local norminette = require("highlight-norminette")
norminette.setup()
vim.api.nvim_create_user_command(0, "NormeEnable", norminette.enable(), {})
vim.api.nvim_create_user_command(0, "NormeDisable", norminette.disable(), {})
vim.api.nvim_create_user_command(0, "NormeToggle", norminette.toggle(), {})
